#!/usr/bin/env bash
set -euox pipefail

export LLVM_PROFILE_FILE="$(realpath ./_build)"/cov.profraw

do-install-deps() {
  sudo apt update
  sudo apt install $AIOXX_DEPS
}

do-clean() {
  rm -rf ./_build
}

do-configure() {
  cmake -B ./_build \
    -DCMAKE_BUILD_TYPE="$AIOXX_BUILD" \
    -DCMAKE_CXX_COMPILER="$AIOXX_CXX" \
    -DCMAKE_C_COMPILER="$AIOXX_CC" \
    -DCMAKE_ASM_COMPILER="$AIOXX_CC" \
    -DCMAKE_CXX_FLAGS="$AIOXX_FLAGS" \
    -DCMAKE_C_FLAGS="$AIOXX_FLAGS"
}

do-build() {
  cmake --build ./_build
}

do-test() {
  ctest --test-dir ./_build ||
    ctest --test-dir ./_build --rerun-failed --output-on-failure
}

do-cover() {
  ./_build/aio-ut
  AIOXX_LLVM_BIN="${AIOXX_LLVM_BIN:-/usr/bin}"
  "${AIOXX_LLVM_BIN}/llvm-profdata" merge \
    -sparse "$LLVM_PROFILE_FILE" \
    -o ./_build/cov.profdata
  "${AIOXX_LLVM_BIN}/llvm-cov" report ./_build/aio-ut \
    -instr-profile=./_build/cov.profdata \
    -show-region-summary=false \
    -ignore-filename-regex='_build/_deps/' \
    -ignore-filename-regex='ut/'
}

do-"$1" ${@:2}