name: Build and test CMake project (Ubuntu)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: ci/pipeline install-deps clang-19

      - name: Configure project
        run: AIOXX_CC=clang-19 AIOXX_CXX=clang++-19 ci/pipeline configure

      - name: Build project
        run: ci/pipeline build

      - name: Run unit tests
        run: ci/pipeline test