name: 'PR & Post-Commit'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-debug:
    runs-on: ubuntu-latest
    env:
      AIOXX_CC: clang-19
      AIOXX_CXX: clang++-19
    steps:
      - uses: actions/checkout@v4
      - run: ci/pipeline install-deps "$AIOXX_CC"
      - run: ci/pipeline configure
      - run: ci/pipeline build
      - run: ci/pipeline test