name: 'PR & Push'


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  ubuntu-amd64-clang18-debug-san:
    runs-on: ubuntu-latest
    env:
      AIOXX_CC: clang-18
      AIOXX_CXX: clang++-18
      AIOXX_DEPS: clang-18 libc++-18-dev
      AIOXX_BUILD: Debug
      AIOXX_FLAGS: -fsanitize=undefined,address -stdlib=libc++
    steps:
      - uses: actions/checkout@v4
      - run: ci/pipeline install-deps
      - run: ci/pipeline configure
      - run: ci/pipeline build
      - run: ci/pipeline test

  ubuntu-amd64-clang18-debug-cov:
    runs-on: ubuntu-latest
    env:
      AIOXX_CC: clang-18
      AIOXX_CXX: clang++-18
      AIOXX_DEPS: clang-18 llvm-18 libc++-18-dev
      AIOXX_BUILD: Debug
      AIOXX_FLAGS: -fcoverage-mapping -fprofile-instr-generate -O0 -stdlib=libc++
      AIOXX_LLVM_BIN: /usr/lib/llvm-18/bin
    steps:
      - uses: actions/checkout@v4
      - run: ci/pipeline install-deps
      - run: ci/pipeline configure
      - run: ci/pipeline build
      - run: ci/pipeline test
      - run: ci/pipeline cover

  ubuntu-amd64-clang18-relwithdebinfo:
    runs-on: ubuntu-latest
    env:
      AIOXX_CC: clang-18
      AIOXX_CXX: clang++-18
      AIOXX_DEPS: clang-18 libc++-18-dev
      AIOXX_BUILD: RelWithDebInfo
      AIOXX_FLAGS: -stdlib=libc++
    steps:
      - uses: actions/checkout@v4
      - run: ci/pipeline install-deps
      - run: ci/pipeline configure
      - run: ci/pipeline build
      - run: ci/pipeline test